using System.Diagnostics.CodeAnalysis;

namespace UrlShortener.Core.Links;

/// <summary>
/// The format of a generated short code: 7 characters from the Base58 alphabet.
/// Base58 leaves out 0, O, I and l, which look alike when a code is read aloud, printed or typed.
/// See docs/prompts/GF-02-domain-core.md for the full reasoning.
/// </summary>
public static class ShortCode
{
    public const string Alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
    public const int Length = 7;

    /// <summary>True when <paramref name="code"/> could have been generated by us.</summary>
    public static bool IsGenerated([NotNullWhen(true)] string? code) =>
        code is { Length: Length } && code.All(c => Alphabet.Contains(c, StringComparison.Ordinal));

    /// <summary>
    /// True when <paramref name="code"/> is a generated code or has the shape of a custom alias (AB-03b).
    /// Used to reject garbage before it reaches the database.
    /// </summary>
    public static bool IsWellFormed([NotNullWhen(true)] string? code) =>
        IsGenerated(code) || AliasRules.HasAliasShape(code);
}
